version: "3.1"

services:

  db:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "edmofarias@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - postgres-compose-network

  web:
    image: php:7.3.7-apache
    container_name: web
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 8080:80
    stdin_open: true
    tty: true

networks:
  postgres-compose-network:
    driver: bridge